2018-11-29 14:31:06,112 ERROR: Exception on /user/kaori [GET] [in /home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaori/Desktop/flasky/app/routes.py", line 73, in user
    return render_template('user.html',user=user,posts=posts)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kaori/Desktop/flasky/app/templates/user.html", line 18, in template
    {% elif not current_user.is_following(user) %}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-11-29 14:31:16,327 ERROR: Exception on /user/kaori [GET] [in /home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaori/Desktop/flasky/app/routes.py", line 73, in user
    return render_template('user.html',user=user,posts=posts)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kaori/Desktop/flasky/app/templates/user.html", line 18, in template
    {% elif not current_user.is_following(user) %}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-11-29 14:32:23,932 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 14:33:48,527 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 14:35:20,471 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 14:37:04,543 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 14:38:18,882 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
